### ISSUE TITLE
HTML type

### ISSUE THREAD

**Issue by kishor10d** [techlab/codeigniter-smartgrid#2]
Hello,
If I want EDIT and DELETE button in smartgrid, then how to do that?

You provided ```html``` type in your documentation, but there is no documentation to use it or any demo for that.

**Comment by techlab** [comment]
You need to use `custom` type column.

`$columns = array(   
"field_name"=>array("type"=>"custom", "header"=>"Buttons", "field_data"=>'<button type="button" class="btn btn-default btn-xs" value="{field_name}">EDIT</button> <button type="button" class="btn btn-danger btn-xs" value="{field_name}">DELETE</button>', "align"=>"center", "width"=>"") 
);`
